// Generated by gencpp from file hebi_cpp_api_examples/SetGains.msg
// DO NOT EDIT!


#ifndef HEBI_CPP_API_EXAMPLES_MESSAGE_SETGAINS_H
#define HEBI_CPP_API_EXAMPLES_MESSAGE_SETGAINS_H

#include <ros/service_traits.h>


#include <hebi_cpp_api_examples/SetGainsRequest.h>
#include <hebi_cpp_api_examples/SetGainsResponse.h>


namespace hebi_cpp_api_examples
{

struct SetGains
{

typedef SetGainsRequest Request;
typedef SetGainsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGains
} // namespace hebi_cpp_api_examples


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hebi_cpp_api_examples::SetGains > {
  static const char* value()
  {
    return "4fedf26e82cd5de1e91a4ab742d58b2c";
  }

  static const char* value(const ::hebi_cpp_api_examples::SetGains&) { return value(); }
};

template<>
struct DataType< ::hebi_cpp_api_examples::SetGains > {
  static const char* value()
  {
    return "hebi_cpp_api_examples/SetGains";
  }

  static const char* value(const ::hebi_cpp_api_examples::SetGains&) { return value(); }
};


// service_traits::MD5Sum< ::hebi_cpp_api_examples::SetGainsRequest> should match
// service_traits::MD5Sum< ::hebi_cpp_api_examples::SetGains >
template<>
struct MD5Sum< ::hebi_cpp_api_examples::SetGainsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hebi_cpp_api_examples::SetGains >::value();
  }
  static const char* value(const ::hebi_cpp_api_examples::SetGainsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebi_cpp_api_examples::SetGainsRequest> should match
// service_traits::DataType< ::hebi_cpp_api_examples::SetGains >
template<>
struct DataType< ::hebi_cpp_api_examples::SetGainsRequest>
{
  static const char* value()
  {
    return DataType< ::hebi_cpp_api_examples::SetGains >::value();
  }
  static const char* value(const ::hebi_cpp_api_examples::SetGainsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hebi_cpp_api_examples::SetGainsResponse> should match
// service_traits::MD5Sum< ::hebi_cpp_api_examples::SetGains >
template<>
struct MD5Sum< ::hebi_cpp_api_examples::SetGainsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hebi_cpp_api_examples::SetGains >::value();
  }
  static const char* value(const ::hebi_cpp_api_examples::SetGainsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebi_cpp_api_examples::SetGainsResponse> should match
// service_traits::DataType< ::hebi_cpp_api_examples::SetGains >
template<>
struct DataType< ::hebi_cpp_api_examples::SetGainsResponse>
{
  static const char* value()
  {
    return DataType< ::hebi_cpp_api_examples::SetGains >::value();
  }
  static const char* value(const ::hebi_cpp_api_examples::SetGainsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HEBI_CPP_API_EXAMPLES_MESSAGE_SETGAINS_H
