// Generated by gencpp from file hebi_cpp_api_examples/SetIKSeed.msg
// DO NOT EDIT!


#ifndef HEBI_CPP_API_EXAMPLES_MESSAGE_SETIKSEED_H
#define HEBI_CPP_API_EXAMPLES_MESSAGE_SETIKSEED_H

#include <ros/service_traits.h>


#include <hebi_cpp_api_examples/SetIKSeedRequest.h>
#include <hebi_cpp_api_examples/SetIKSeedResponse.h>


namespace hebi_cpp_api_examples
{

struct SetIKSeed
{

typedef SetIKSeedRequest Request;
typedef SetIKSeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetIKSeed
} // namespace hebi_cpp_api_examples


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hebi_cpp_api_examples::SetIKSeed > {
  static const char* value()
  {
    return "45f70114af10b3f5f5e2b664d72ca331";
  }

  static const char* value(const ::hebi_cpp_api_examples::SetIKSeed&) { return value(); }
};

template<>
struct DataType< ::hebi_cpp_api_examples::SetIKSeed > {
  static const char* value()
  {
    return "hebi_cpp_api_examples/SetIKSeed";
  }

  static const char* value(const ::hebi_cpp_api_examples::SetIKSeed&) { return value(); }
};


// service_traits::MD5Sum< ::hebi_cpp_api_examples::SetIKSeedRequest> should match
// service_traits::MD5Sum< ::hebi_cpp_api_examples::SetIKSeed >
template<>
struct MD5Sum< ::hebi_cpp_api_examples::SetIKSeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hebi_cpp_api_examples::SetIKSeed >::value();
  }
  static const char* value(const ::hebi_cpp_api_examples::SetIKSeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebi_cpp_api_examples::SetIKSeedRequest> should match
// service_traits::DataType< ::hebi_cpp_api_examples::SetIKSeed >
template<>
struct DataType< ::hebi_cpp_api_examples::SetIKSeedRequest>
{
  static const char* value()
  {
    return DataType< ::hebi_cpp_api_examples::SetIKSeed >::value();
  }
  static const char* value(const ::hebi_cpp_api_examples::SetIKSeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hebi_cpp_api_examples::SetIKSeedResponse> should match
// service_traits::MD5Sum< ::hebi_cpp_api_examples::SetIKSeed >
template<>
struct MD5Sum< ::hebi_cpp_api_examples::SetIKSeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hebi_cpp_api_examples::SetIKSeed >::value();
  }
  static const char* value(const ::hebi_cpp_api_examples::SetIKSeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebi_cpp_api_examples::SetIKSeedResponse> should match
// service_traits::DataType< ::hebi_cpp_api_examples::SetIKSeed >
template<>
struct DataType< ::hebi_cpp_api_examples::SetIKSeedResponse>
{
  static const char* value()
  {
    return DataType< ::hebi_cpp_api_examples::SetIKSeed >::value();
  }
  static const char* value(const ::hebi_cpp_api_examples::SetIKSeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HEBI_CPP_API_EXAMPLES_MESSAGE_SETIKSEED_H
