// Generated by gencpp from file hebi_cpp_api_examples/SetIKSeedRequest.msg
// DO NOT EDIT!


#ifndef HEBI_CPP_API_EXAMPLES_MESSAGE_SETIKSEEDREQUEST_H
#define HEBI_CPP_API_EXAMPLES_MESSAGE_SETIKSEEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hebi_cpp_api_examples
{
template <class ContainerAllocator>
struct SetIKSeedRequest_
{
  typedef SetIKSeedRequest_<ContainerAllocator> Type;

  SetIKSeedRequest_()
    : seed()  {
    }
  SetIKSeedRequest_(const ContainerAllocator& _alloc)
    : seed(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _seed_type;
  _seed_type seed;





  typedef boost::shared_ptr< ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetIKSeedRequest_

typedef ::hebi_cpp_api_examples::SetIKSeedRequest_<std::allocator<void> > SetIKSeedRequest;

typedef boost::shared_ptr< ::hebi_cpp_api_examples::SetIKSeedRequest > SetIKSeedRequestPtr;
typedef boost::shared_ptr< ::hebi_cpp_api_examples::SetIKSeedRequest const> SetIKSeedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator1> & lhs, const ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator2> & rhs)
{
  return lhs.seed == rhs.seed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator1> & lhs, const ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hebi_cpp_api_examples

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "45f70114af10b3f5f5e2b664d72ca331";
  }

  static const char* value(const ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x45f70114af10b3f5ULL;
  static const uint64_t static_value2 = 0xf5e2b664d72ca331ULL;
};

template<class ContainerAllocator>
struct DataType< ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hebi_cpp_api_examples/SetIKSeedRequest";
  }

  static const char* value(const ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] seed\n"
;
  }

  static const char* value(const ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.seed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetIKSeedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hebi_cpp_api_examples::SetIKSeedRequest_<ContainerAllocator>& v)
  {
    s << indent << "seed[]" << std::endl;
    for (size_t i = 0; i < v.seed.size(); ++i)
    {
      s << indent << "  seed[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.seed[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEBI_CPP_API_EXAMPLES_MESSAGE_SETIKSEEDREQUEST_H
