; Auto-generated. Do not edit!


(cl:in-package hebi_cpp_api_examples-msg)


;//! \htmlinclude ArmMotionResult.msg.html

(cl:defclass <ArmMotionResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass ArmMotionResult (<ArmMotionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ArmMotionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ArmMotionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hebi_cpp_api_examples-msg:<ArmMotionResult> is deprecated: use hebi_cpp_api_examples-msg:ArmMotionResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ArmMotionResult>) ostream)
  "Serializes a message object of type '<ArmMotionResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ArmMotionResult>) istream)
  "Deserializes a message object of type '<ArmMotionResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ArmMotionResult>)))
  "Returns string type for a message object of type '<ArmMotionResult>"
  "hebi_cpp_api_examples/ArmMotionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ArmMotionResult)))
  "Returns string type for a message object of type 'ArmMotionResult"
  "hebi_cpp_api_examples/ArmMotionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ArmMotionResult>)))
  "Returns md5sum for a message object of type '<ArmMotionResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ArmMotionResult)))
  "Returns md5sum for a message object of type 'ArmMotionResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ArmMotionResult>)))
  "Returns full string definition for message of type '<ArmMotionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ArmMotionResult)))
  "Returns full string definition for message of type 'ArmMotionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ArmMotionResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ArmMotionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ArmMotionResult
))
