; Auto-generated. Do not edit!


(cl:in-package hebi_cpp_api_examples-msg)


;//! \htmlinclude BaseMotionResult.msg.html

(cl:defclass <BaseMotionResult> (roslisp-msg-protocol:ros-message)
  ((success
    :reader success
    :initarg :success
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass BaseMotionResult (<BaseMotionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BaseMotionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BaseMotionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hebi_cpp_api_examples-msg:<BaseMotionResult> is deprecated: use hebi_cpp_api_examples-msg:BaseMotionResult instead.")))

(cl:ensure-generic-function 'success-val :lambda-list '(m))
(cl:defmethod success-val ((m <BaseMotionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hebi_cpp_api_examples-msg:success-val is deprecated.  Use hebi_cpp_api_examples-msg:success instead.")
  (success m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BaseMotionResult>) ostream)
  "Serializes a message object of type '<BaseMotionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'success) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BaseMotionResult>) istream)
  "Deserializes a message object of type '<BaseMotionResult>"
    (cl:setf (cl:slot-value msg 'success) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BaseMotionResult>)))
  "Returns string type for a message object of type '<BaseMotionResult>"
  "hebi_cpp_api_examples/BaseMotionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BaseMotionResult)))
  "Returns string type for a message object of type 'BaseMotionResult"
  "hebi_cpp_api_examples/BaseMotionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BaseMotionResult>)))
  "Returns md5sum for a message object of type '<BaseMotionResult>"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BaseMotionResult)))
  "Returns md5sum for a message object of type 'BaseMotionResult"
  "358e233cde0c8a8bcfea4ce193f8fc15")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BaseMotionResult>)))
  "Returns full string definition for message of type '<BaseMotionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BaseMotionResult)))
  "Returns full string definition for message of type 'BaseMotionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%bool success~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BaseMotionResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BaseMotionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'BaseMotionResult
    (cl:cons ':success (success msg))
))
