// Generated by gencpp from file hebi_cpp_api_examples/SetCommandLifetimeRequest.msg
// DO NOT EDIT!


#ifndef HEBI_CPP_API_EXAMPLES_MESSAGE_SETCOMMANDLIFETIMEREQUEST_H
#define HEBI_CPP_API_EXAMPLES_MESSAGE_SETCOMMANDLIFETIMEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hebi_cpp_api_examples
{
template <class ContainerAllocator>
struct SetCommandLifetimeRequest_
{
  typedef SetCommandLifetimeRequest_<ContainerAllocator> Type;

  SetCommandLifetimeRequest_()
    : lifetime()  {
    }
  SetCommandLifetimeRequest_(const ContainerAllocator& _alloc)
    : lifetime()  {
  (void)_alloc;
    }



   typedef ros::Duration _lifetime_type;
  _lifetime_type lifetime;





  typedef boost::shared_ptr< ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetCommandLifetimeRequest_

typedef ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<std::allocator<void> > SetCommandLifetimeRequest;

typedef boost::shared_ptr< ::hebi_cpp_api_examples::SetCommandLifetimeRequest > SetCommandLifetimeRequestPtr;
typedef boost::shared_ptr< ::hebi_cpp_api_examples::SetCommandLifetimeRequest const> SetCommandLifetimeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator1> & lhs, const ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.lifetime == rhs.lifetime;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator1> & lhs, const ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hebi_cpp_api_examples

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0659a04e68b42bafc22572c92df4e2e3";
  }

  static const char* value(const ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0659a04e68b42bafULL;
  static const uint64_t static_value2 = 0xc22572c92df4e2e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hebi_cpp_api_examples/SetCommandLifetimeRequest";
  }

  static const char* value(const ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duration lifetime\n"
;
  }

  static const char* value(const ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.lifetime);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCommandLifetimeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hebi_cpp_api_examples::SetCommandLifetimeRequest_<ContainerAllocator>& v)
  {
    s << indent << "lifetime: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.lifetime);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEBI_CPP_API_EXAMPLES_MESSAGE_SETCOMMANDLIFETIMEREQUEST_H
