// Generated by gencpp from file hebi_cpp_api_examples/SetGainsRequest.msg
// DO NOT EDIT!


#ifndef HEBI_CPP_API_EXAMPLES_MESSAGE_SETGAINSREQUEST_H
#define HEBI_CPP_API_EXAMPLES_MESSAGE_SETGAINSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hebi_cpp_api_examples
{
template <class ContainerAllocator>
struct SetGainsRequest_
{
  typedef SetGainsRequest_<ContainerAllocator> Type;

  SetGainsRequest_()
    : gains_package()
    , gains_file()  {
    }
  SetGainsRequest_(const ContainerAllocator& _alloc)
    : gains_package(_alloc)
    , gains_file(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _gains_package_type;
  _gains_package_type gains_package;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _gains_file_type;
  _gains_file_type gains_file;





  typedef boost::shared_ptr< ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetGainsRequest_

typedef ::hebi_cpp_api_examples::SetGainsRequest_<std::allocator<void> > SetGainsRequest;

typedef boost::shared_ptr< ::hebi_cpp_api_examples::SetGainsRequest > SetGainsRequestPtr;
typedef boost::shared_ptr< ::hebi_cpp_api_examples::SetGainsRequest const> SetGainsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator1> & lhs, const ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.gains_package == rhs.gains_package &&
    lhs.gains_file == rhs.gains_file;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator1> & lhs, const ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hebi_cpp_api_examples

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fedf26e82cd5de1e91a4ab742d58b2c";
  }

  static const char* value(const ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fedf26e82cd5de1ULL;
  static const uint64_t static_value2 = 0xe91a4ab742d58b2cULL;
};

template<class ContainerAllocator>
struct DataType< ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hebi_cpp_api_examples/SetGainsRequest";
  }

  static const char* value(const ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string gains_package\n"
"string gains_file\n"
;
  }

  static const char* value(const ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gains_package);
      stream.next(m.gains_file);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetGainsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hebi_cpp_api_examples::SetGainsRequest_<ContainerAllocator>& v)
  {
    s << indent << "gains_package: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.gains_package);
    s << indent << "gains_file: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.gains_file);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEBI_CPP_API_EXAMPLES_MESSAGE_SETGAINSREQUEST_H
