// Generated by gencpp from file coborg_move/CartesianTrajectory.msg
// DO NOT EDIT!


#ifndef COBORG_MOVE_MESSAGE_CARTESIANTRAJECTORY_H
#define COBORG_MOVE_MESSAGE_CARTESIANTRAJECTORY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace coborg_move
{
template <class ContainerAllocator>
struct CartesianTrajectory_
{
  typedef CartesianTrajectory_<ContainerAllocator> Type;

  CartesianTrajectory_()
    : header()
    , origin()
    , goal()  {
    }
  CartesianTrajectory_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , origin(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _origin_type;
  _origin_type origin;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::coborg_move::CartesianTrajectory_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::coborg_move::CartesianTrajectory_<ContainerAllocator> const> ConstPtr;

}; // struct CartesianTrajectory_

typedef ::coborg_move::CartesianTrajectory_<std::allocator<void> > CartesianTrajectory;

typedef boost::shared_ptr< ::coborg_move::CartesianTrajectory > CartesianTrajectoryPtr;
typedef boost::shared_ptr< ::coborg_move::CartesianTrajectory const> CartesianTrajectoryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::coborg_move::CartesianTrajectory_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::coborg_move::CartesianTrajectory_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::coborg_move::CartesianTrajectory_<ContainerAllocator1> & lhs, const ::coborg_move::CartesianTrajectory_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.origin == rhs.origin &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::coborg_move::CartesianTrajectory_<ContainerAllocator1> & lhs, const ::coborg_move::CartesianTrajectory_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace coborg_move

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::coborg_move::CartesianTrajectory_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::coborg_move::CartesianTrajectory_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coborg_move::CartesianTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::coborg_move::CartesianTrajectory_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coborg_move::CartesianTrajectory_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::coborg_move::CartesianTrajectory_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::coborg_move::CartesianTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e4f7ea05e9c61043107bec8842a0fd90";
  }

  static const char* value(const ::coborg_move::CartesianTrajectory_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe4f7ea05e9c61043ULL;
  static const uint64_t static_value2 = 0x107bec8842a0fd90ULL;
};

template<class ContainerAllocator>
struct DataType< ::coborg_move::CartesianTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "coborg_move/CartesianTrajectory";
  }

  static const char* value(const ::coborg_move::CartesianTrajectory_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::coborg_move::CartesianTrajectory_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Pose origin\n"
"geometry_msgs/Pose goal\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::coborg_move::CartesianTrajectory_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::coborg_move::CartesianTrajectory_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.origin);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CartesianTrajectory_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::coborg_move::CartesianTrajectory_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::coborg_move::CartesianTrajectory_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "origin: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.origin);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COBORG_MOVE_MESSAGE_CARTESIANTRAJECTORY_H
