// Generated by gencpp from file goal_getter/goal_msg.msg
// DO NOT EDIT!


#ifndef GOAL_GETTER_MESSAGE_GOAL_MSG_H
#define GOAL_GETTER_MESSAGE_GOAL_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace goal_getter
{
template <class ContainerAllocator>
struct goal_msg_
{
  typedef goal_msg_<ContainerAllocator> Type;

  goal_msg_()
    : Class()
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  goal_msg_(const ContainerAllocator& _alloc)
    : Class(_alloc)
    , x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Class_type;
  _Class_type Class;

   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::goal_getter::goal_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::goal_getter::goal_msg_<ContainerAllocator> const> ConstPtr;

}; // struct goal_msg_

typedef ::goal_getter::goal_msg_<std::allocator<void> > goal_msg;

typedef boost::shared_ptr< ::goal_getter::goal_msg > goal_msgPtr;
typedef boost::shared_ptr< ::goal_getter::goal_msg const> goal_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::goal_getter::goal_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::goal_getter::goal_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::goal_getter::goal_msg_<ContainerAllocator1> & lhs, const ::goal_getter::goal_msg_<ContainerAllocator2> & rhs)
{
  return lhs.Class == rhs.Class &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::goal_getter::goal_msg_<ContainerAllocator1> & lhs, const ::goal_getter::goal_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace goal_getter

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::goal_getter::goal_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::goal_getter::goal_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::goal_getter::goal_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::goal_getter::goal_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::goal_getter::goal_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::goal_getter::goal_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::goal_getter::goal_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1995ab0b6624278887ba1c25d7923c9c";
  }

  static const char* value(const ::goal_getter::goal_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1995ab0b66242788ULL;
  static const uint64_t static_value2 = 0x87ba1c25d7923c9cULL;
};

template<class ContainerAllocator>
struct DataType< ::goal_getter::goal_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "goal_getter/goal_msg";
  }

  static const char* value(const ::goal_getter::goal_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::goal_getter::goal_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Class\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
;
  }

  static const char* value(const ::goal_getter::goal_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::goal_getter::goal_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Class);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goal_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::goal_getter::goal_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::goal_getter::goal_msg_<ContainerAllocator>& v)
  {
    s << indent << "Class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Class);
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GOAL_GETTER_MESSAGE_GOAL_MSG_H
