(cl:defpackage hebi_cpp_api_examples-srv
  (:use )
  (:export
   "SETCOMMANDLIFETIME"
   "<SETCOMMANDLIFETIME-REQUEST>"
   "SETCOMMANDLIFETIME-REQUEST"
   "<SETCOMMANDLIFETIME-RESPONSE>"
   "SETCOMMANDLIFETIME-RESPONSE"
   "SETFEEDBACKFREQUENCY"
   "<SETFEEDBACKFREQUENCY-REQUEST>"
   "SETFEEDBACKFREQUENCY-REQUEST"
   "<SETFEEDBACKFREQUENCY-RESPONSE>"
   "SETFEEDBACKFREQUENCY-RESPONSE"
   "SETGAINS"
   "<SETGAINS-REQUEST>"
   "SETGAINS-REQUEST"
   "<SETGAINS-RESPONSE>"
   "SETGAINS-RESPONSE"
   "SETIKSEED"
   "<SETIKSEED-REQUEST>"
   "SETIKSEED-REQUEST"
   "<SETIKSEED-RESPONSE>"
   "SETIKSEED-RESPONSE"
  ))

