; Auto-generated. Do not edit!


(cl:in-package hebi_cpp_api_examples-msg)


;//! \htmlinclude BaseMotionFeedback.msg.html

(cl:defclass <BaseMotionFeedback> (roslisp-msg-protocol:ros-message)
  ((percent_complete
    :reader percent_complete
    :initarg :percent_complete
    :type cl:float
    :initform 0.0))
)

(cl:defclass BaseMotionFeedback (<BaseMotionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BaseMotionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BaseMotionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name hebi_cpp_api_examples-msg:<BaseMotionFeedback> is deprecated: use hebi_cpp_api_examples-msg:BaseMotionFeedback instead.")))

(cl:ensure-generic-function 'percent_complete-val :lambda-list '(m))
(cl:defmethod percent_complete-val ((m <BaseMotionFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader hebi_cpp_api_examples-msg:percent_complete-val is deprecated.  Use hebi_cpp_api_examples-msg:percent_complete instead.")
  (percent_complete m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BaseMotionFeedback>) ostream)
  "Serializes a message object of type '<BaseMotionFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'percent_complete))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BaseMotionFeedback>) istream)
  "Deserializes a message object of type '<BaseMotionFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent_complete) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BaseMotionFeedback>)))
  "Returns string type for a message object of type '<BaseMotionFeedback>"
  "hebi_cpp_api_examples/BaseMotionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BaseMotionFeedback)))
  "Returns string type for a message object of type 'BaseMotionFeedback"
  "hebi_cpp_api_examples/BaseMotionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BaseMotionFeedback>)))
  "Returns md5sum for a message object of type '<BaseMotionFeedback>"
  "cc6abe8bc172f00995b2c3f53015f718")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BaseMotionFeedback)))
  "Returns md5sum for a message object of type 'BaseMotionFeedback"
  "cc6abe8bc172f00995b2c3f53015f718")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BaseMotionFeedback>)))
  "Returns full string definition for message of type '<BaseMotionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 percent_complete~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BaseMotionFeedback)))
  "Returns full string definition for message of type 'BaseMotionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%float64 percent_complete~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BaseMotionFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BaseMotionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'BaseMotionFeedback
    (cl:cons ':percent_complete (percent_complete msg))
))
