# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  motor1/X5_9:
    has_velocity_limits: true
    max_velocity: 14
    has_acceleration_limits: false
    max_acceleration: 0
  motor2/X5_9:
    has_velocity_limits: true
    max_velocity: 14
    has_acceleration_limits: false
    max_acceleration: 0
  motor3/X5_9:
    has_velocity_limits: true
    max_velocity: 14
    has_acceleration_limits: false
    max_acceleration: 0
  motor4/X5_9:
    has_velocity_limits: true
    max_velocity: 14
    has_acceleration_limits: false
    max_acceleration: 0
  motor5/X5_4:
    has_velocity_limits: true
    max_velocity: 32
    has_acceleration_limits: false
    max_acceleration: 0