// Generated by gencpp from file hebi_cpp_api_examples/SetCommandLifetime.msg
// DO NOT EDIT!


#ifndef HEBI_CPP_API_EXAMPLES_MESSAGE_SETCOMMANDLIFETIME_H
#define HEBI_CPP_API_EXAMPLES_MESSAGE_SETCOMMANDLIFETIME_H

#include <ros/service_traits.h>


#include <hebi_cpp_api_examples/SetCommandLifetimeRequest.h>
#include <hebi_cpp_api_examples/SetCommandLifetimeResponse.h>


namespace hebi_cpp_api_examples
{

struct SetCommandLifetime
{

typedef SetCommandLifetimeRequest Request;
typedef SetCommandLifetimeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetCommandLifetime
} // namespace hebi_cpp_api_examples


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::hebi_cpp_api_examples::SetCommandLifetime > {
  static const char* value()
  {
    return "0659a04e68b42bafc22572c92df4e2e3";
  }

  static const char* value(const ::hebi_cpp_api_examples::SetCommandLifetime&) { return value(); }
};

template<>
struct DataType< ::hebi_cpp_api_examples::SetCommandLifetime > {
  static const char* value()
  {
    return "hebi_cpp_api_examples/SetCommandLifetime";
  }

  static const char* value(const ::hebi_cpp_api_examples::SetCommandLifetime&) { return value(); }
};


// service_traits::MD5Sum< ::hebi_cpp_api_examples::SetCommandLifetimeRequest> should match
// service_traits::MD5Sum< ::hebi_cpp_api_examples::SetCommandLifetime >
template<>
struct MD5Sum< ::hebi_cpp_api_examples::SetCommandLifetimeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::hebi_cpp_api_examples::SetCommandLifetime >::value();
  }
  static const char* value(const ::hebi_cpp_api_examples::SetCommandLifetimeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebi_cpp_api_examples::SetCommandLifetimeRequest> should match
// service_traits::DataType< ::hebi_cpp_api_examples::SetCommandLifetime >
template<>
struct DataType< ::hebi_cpp_api_examples::SetCommandLifetimeRequest>
{
  static const char* value()
  {
    return DataType< ::hebi_cpp_api_examples::SetCommandLifetime >::value();
  }
  static const char* value(const ::hebi_cpp_api_examples::SetCommandLifetimeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::hebi_cpp_api_examples::SetCommandLifetimeResponse> should match
// service_traits::MD5Sum< ::hebi_cpp_api_examples::SetCommandLifetime >
template<>
struct MD5Sum< ::hebi_cpp_api_examples::SetCommandLifetimeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::hebi_cpp_api_examples::SetCommandLifetime >::value();
  }
  static const char* value(const ::hebi_cpp_api_examples::SetCommandLifetimeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::hebi_cpp_api_examples::SetCommandLifetimeResponse> should match
// service_traits::DataType< ::hebi_cpp_api_examples::SetCommandLifetime >
template<>
struct DataType< ::hebi_cpp_api_examples::SetCommandLifetimeResponse>
{
  static const char* value()
  {
    return DataType< ::hebi_cpp_api_examples::SetCommandLifetime >::value();
  }
  static const char* value(const ::hebi_cpp_api_examples::SetCommandLifetimeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // HEBI_CPP_API_EXAMPLES_MESSAGE_SETCOMMANDLIFETIME_H
