// Generated by gencpp from file hebi_cpp_api_examples/SetFeedbackFrequencyRequest.msg
// DO NOT EDIT!


#ifndef HEBI_CPP_API_EXAMPLES_MESSAGE_SETFEEDBACKFREQUENCYREQUEST_H
#define HEBI_CPP_API_EXAMPLES_MESSAGE_SETFEEDBACKFREQUENCYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hebi_cpp_api_examples
{
template <class ContainerAllocator>
struct SetFeedbackFrequencyRequest_
{
  typedef SetFeedbackFrequencyRequest_<ContainerAllocator> Type;

  SetFeedbackFrequencyRequest_()
    : frequency_hz(0.0)  {
    }
  SetFeedbackFrequencyRequest_(const ContainerAllocator& _alloc)
    : frequency_hz(0.0)  {
  (void)_alloc;
    }



   typedef double _frequency_hz_type;
  _frequency_hz_type frequency_hz;





  typedef boost::shared_ptr< ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetFeedbackFrequencyRequest_

typedef ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<std::allocator<void> > SetFeedbackFrequencyRequest;

typedef boost::shared_ptr< ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest > SetFeedbackFrequencyRequestPtr;
typedef boost::shared_ptr< ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest const> SetFeedbackFrequencyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator1> & lhs, const ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator2> & rhs)
{
  return lhs.frequency_hz == rhs.frequency_hz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator1> & lhs, const ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace hebi_cpp_api_examples

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b11146fd2143e78325a7496114ee3a9e";
  }

  static const char* value(const ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb11146fd2143e783ULL;
  static const uint64_t static_value2 = 0x25a7496114ee3a9eULL;
};

template<class ContainerAllocator>
struct DataType< ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hebi_cpp_api_examples/SetFeedbackFrequencyRequest";
  }

  static const char* value(const ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 frequency_hz\n"
;
  }

  static const char* value(const ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frequency_hz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetFeedbackFrequencyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hebi_cpp_api_examples::SetFeedbackFrequencyRequest_<ContainerAllocator>& v)
  {
    s << indent << "frequency_hz: ";
    Printer<double>::stream(s, indent + "  ", v.frequency_hz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HEBI_CPP_API_EXAMPLES_MESSAGE_SETFEEDBACKFREQUENCYREQUEST_H
