controller_list:
  - name: fake_dof_4_4inchlower_arm_controller
    joints:
      - motor1/X5_9
      - motor2/X5_9
      - motor3/X5_9
      - motor4/X5_4
initial:  # Define initial robot poses.
  - group: dof_4_4inchlower_arm
    pose: arm_out